---
abstract: "It's new $module, this can handle a Docker image for tests."
author:
  - 'Motonori Iwata <gootonroi+github@gmail.com>'
build_requires:
  Test::Mock::Guard: '0.10'
  Test::More: '0.98'
  Test::UseAllModules: '0.15'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Docker-Image
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Test::Docker::Image:
    file: lib/Test/Docker/Image.pm
    version: '0.01'
  Test::Docker::Image::Boot:
    file: lib/Test/Docker/Image/Boot.pm
  Test::Docker::Image::Boot::Boot2docker:
    file: lib/Test/Docker/Image/Boot/Boot2docker.pm
requires:
  Class::Accessor::Lite: '0.06'
  Class::Load: '0.22'
  Data::Util: '0.63'
  IPC::Run3: '0.048'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/iwata/p5-Test-Docker-Image/issues
  homepage: https://github.com/iwata/p5-Test-Docker-Image
  repository: git://github.com/iwata/p5-Test-Docker-Image.git
version: '0.01'
x_contributors:
  - 'iwata-motonori <motonori.iwata@dena.com>'
  - 'Motonori Iwata <gootonori+github@gmail.com>'
